###################################################################################################
# Contains the URL and checksums to download version 5.0.9 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/08f79414-91fe-4072-a75b-7b7c21d0fced/46c49c781f43901eb7c27c465c448b0a/aspnetcore-runtime-5.0.9-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b068e2969e60c577100b20323aac2ef7"
SRC_URI[sha256sum] = "fd975d18ed03d1fa3b9466d763e2f6a569d40a90b82e727eccd2ebb6a11aa3e8"
