###################################################################################################
# Contains the URL and checksums to download version 7.0.0 of the ARM ASP.NET Core runtime from
# Microsoft.
# Original version Copyright Richard Dunkley 2020
# Modified for 7.0.0 by Jan Philipp Giel 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/61cb6649-f41f-4966-84ae-9ff673528054/9bbd07607c5a1af87354e1fa93c36a00/aspnetcore-runtime-7.0.0-linux-arm.tar.gz;subdir=aspnet-${PV}"
SRC_URI[sha512sum] = "560f1a38498f36ccd7429f74e0dfea9e14ab668fc1f916e16542ed3ea4d6a8344f8605143b3c6c8f99248496d77767abedd69a50802d5507324cad44eed6fb1b"
