###################################################################################################
# Contains the URL and checksums to download version 5.0.9 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/19046594-e911-4784-a148-6de3d74d4a7f/d5c1ba792c4266a2d2a8eea41e81a060/aspnetcore-runtime-5.0.9-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "9ee77c5a9ba5f0be16e0efd051890347"
SRC_URI[sha256sum] = "b6cba668bf18981d2274d093a7acaedcd06fbf1929c864650f22f3cf3313481c"
