###################################################################################################
# Contains the URL and checksums to download version 5.0.9 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0e3da9ad-b838-419a-8ad5-caaff159083f/484d306f2778f15519201178961372bc/aspnetcore-runtime-5.0.9-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "952d143e3cf8b831138d1e1c3459a64c"
SRC_URI[sha256sum] = "f1c8486cf0d751447ef8e152fb17e6d4552f2337799625424f403b00ce75801b"
