###################################################################################################
# Contains the URL and checksums to download version 5.0.9 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Jan Philipp Giel 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/75ac6907-d1a1-415d-907d-d5466b2dc4c5/a3bdfe046a226d5ca6f2e129319b2f7b/dotnet-runtime-5.0.9-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "10290c40722b262672a5a3b8da5111a2"
SRC_URI[sha256sum] = "caa2b54245269dbb9ba0a06ef71b02563a976e98e701544f21aca45aacd35af8"

