###################################################################################################
# Contains the URL and checksums to download version 5.0.9 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Jan Philipp Giel 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0c1eabe6-32ef-4785-92d1-8f09a0951b9e/d90c850374a07505bd577d3cff5d7536/dotnet-runtime-5.0.9-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "7da61bbf2cc1ab18b3e936c700f1ed50"
SRC_URI[sha256sum] = "ca143ca29035ebd6acc2b7033d7cdd2b9ceb9e34465ecdb4a7947b92173772ec"
